# This is a basic workflow to help you get started with Actions

name: Run schedule

# Controls when the action will run. 
on:
  schedule:
    - cron: "30 18 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Ping vercel for redeploy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/QmQnT6PJcmBmVzWbss8sTcuosv2oTjpjk98agtsV7MXRKe/KdEp0DOtAh
